language: node_js
node_js:
- lts/*
script:
- npm run lint
- npm run test-with-coverage
env:
  global:
    secure: Yf6Jm1B6Xv9ObmChuCWO9zs/aGoYBSfvZRwh3tAi8NeBg997S4T8tL5hHFZArpWmCCErZVgYBDKlD2LgmuGRajInJ8ndcOBvzHYTfJOtpz6ntK170rUm6BpASTic7V9Jnv78x1uY0LHT7lElGzBZ2TwFzrfb4WIwVbo6L51CqZJy8FoTu/0tIzWx8dxCfBi+YjhTH4kBOg+f7Pmj58Hlo51mxZNAjG/ifNZUzIj5mh7DiLPY9nQVZ7W0hg7avR2rf9xRRF4hPtGo3P2wJa0ffPdUlLc3g90DBDRLk3ySi577cEOPGDx9Nx2TQXIEtp3X9VmdJqGL4lMB4zqKKhg7zYaRy3i7EFO0bi0xDrYp6aZw9oaCLrKeTH+rmjj8xsNjcwS0VsdpqhnhsHIzzzY5LECCw0YxK1jSCxWQi13Cctjq/ATAM4AUyNe0gExl9hD3eBG3J9KFHvBRR4vaeqITMvv2SZRzfEez/mj4EEBuEa75RlUsSMgGr0YMbYBD50yDI1aJLSvgU6KIm15bjaBj7HOlp22MILpa6B7v6i6E0T1HYfCi1RVLaNvg9E7xgFOiUFwIV8bqaHWIqKm7HdkyKJfdthC120E5viM0vhKUZV0h+h58VSzJRWEJBLVV6aWlpLppkVABaj3Bgv6co+CGrdlOI99LfgCC8cfAppXctz0=
